# Generated by Django 6.0.3 on 2026-03-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_cita_compra_productoinventario_proveedor_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoinventario',
            name='stock',
            field=models.BigIntegerField(default=0),
        ),
    ]
