# Generated by Django 4.2.29 on 2026-05-01 01:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('documento', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('clave', models.CharField(max_length=128)),
                ('codigo', models.CharField(max_length=128)),
                ('codigo_expira_en', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-actualizado_en',),
            },
        ),
        migrations.CreateModel(
            name='RecuperacionClave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=128)),
                ('codigo_expira_en', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recuperacion_clave', to='sesiones.usuario')),
            ],
            options={
                'ordering': ('-actualizado_en',),
            },
        ),
    ]
