# Generated by Django 6.0.3 on 2026-03-29 18:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDevolucionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('comentario_admin', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_devolucion_compra', to='sesiones.usuario')),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_devolucion', to='ventas.detalleventa')),
            ],
            options={
                'verbose_name': 'Solicitud de devolucion de venta',
                'verbose_name_plural': 'Solicitudes de devolucion de venta',
                'ordering': ['-fecha_solicitud', '-id'],
            },
        ),
    ]
