# Generated by Django 4.2.29 on 2026-04-14 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('sesiones', '0001_initial'),
        ('ventas', '0002_solicituddevolucionventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='validacionventa',
            name='cliente_invitado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validaciones_venta', to='citas.clienteinvitado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_invitado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='citas.clienteinvitado'),
        ),
        migrations.AddField(
            model_name='venta',
            name='reserva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta_asociada', to='citas.reserva'),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal_servicios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='validacionventa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sesiones.usuario'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sesiones.usuario'),
        ),
    ]
