# Generated by Django 6.0.3 on 2026-06-23 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_validacionventa_cliente_invitado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validacionventa',
            name='cliente_invitado',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente_invitado',
        ),
    ]
