# Generated by Django 4.1.13 on 2026-03-27 12:14

import apps.citas.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteInvitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.BigIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistio')], default='programada', max_length=50)),
                ('origen_reserva', models.CharField(choices=[('invitado', 'Invitado'), ('autenticado', 'Autenticado'), ('admin', 'Administrador')], default='autenticado', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('motivo_cancelacion', models.TextField(blank=True)),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='sesiones.usuario')),
                ('cliente_invitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='citas.clienteinvitado')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_creadas', to='sesiones.usuario')),
            ],
            options={
                'db_table': 'citas_reserva',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_minutos', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15)])),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profesional', models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='citas.profesional')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReservaHistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=50)),
                ('estado_nuevo', models.CharField(max_length=50)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='citas.reserva')),
                ('usuario_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_reserva', to='sesiones.usuario')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='citas.servicio'),
        ),
        migrations.CreateModel(
            name='PagoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('anticipo', 'Anticipo'), ('total', 'Total')], default='total', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('otro', 'Otro')], max_length=30)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('anulado', 'Anulado')], default='confirmado', max_length=20)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_comprobante', models.CharField(default=apps.citas.models._generar_numero_comprobante, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_reserva_registrados', to='sesiones.usuario')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='citas.reserva')),
            ],
            options={
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_inicio'], name='citas_reser_fecha_i_4022af_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='citas_reser_estado_8d3c14_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['origen_reserva'], name='citas_reser_origen__8f43b6_idx'),
        ),
    ]
