# Generated by Django 6.0.2 on 2026-03-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE IF EXISTS citas_cita RENAME TO citas_reserva;",
                    reverse_sql="ALTER TABLE IF EXISTS citas_reserva RENAME TO citas_cita;",
                )
            ],
            state_operations=[
                migrations.RenameModel(
                    old_name="Cita",
                    new_name="Reserva",
                ),
                migrations.AlterModelTable(
                    name="reserva",
                    table="citas_reserva",
                ),
            ],
        ),
    ]
