# Generated by Django 6.0.3 on 2026-03-23 01:31

import apps.citas.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def migrar_persona_servicio_a_profesional(apps, schema_editor):
    Servicio = apps.get_model("citas", "Servicio")
    Profesional = apps.get_model("citas", "Profesional")

    for servicio in Servicio.objects.all():
        nombre_profesional = (getattr(servicio, "persona_servicio", "") or "").strip()
        if not nombre_profesional:
            continue
        profesional, _ = Profesional.objects.get_or_create(nombre=nombre_profesional)
        servicio.profesional = profesional
        servicio.save(update_fields=["profesional"])


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_rename_cita_reserva'),
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('anticipo', 'Anticipo'), ('total', 'Total')], default='total', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('otro', 'Otro')], max_length=30)),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('anulado', 'Anulado')], default='confirmado', max_length=20)),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_comprobante', models.CharField(default=apps.citas.models._generar_numero_comprobante, max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_pago', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReservaHistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=50)),
                ('estado_nuevo', models.CharField(max_length=50)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='reserva',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_creadas', to='sesiones.usuario'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_fin_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_inicio_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='origen_reserva',
            field=models.CharField(choices=[('invitado', 'Invitado'), ('autenticado', 'Autenticado'), ('admin', 'Administrador')], default='autenticado', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='servicio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='sesiones.usuario'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistio')], default='programada', max_length=50),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='citas.servicio'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha_inicio'], name='citas_reser_fecha_i_4022af_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='citas_reser_estado_8d3c14_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['origen_reserva'], name='citas_reser_origen__8f43b6_idx'),
        ),
        migrations.AddField(
            model_name='pagoreserva',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_reserva_registrados', to='sesiones.usuario'),
        ),
        migrations.AddField(
            model_name='pagoreserva',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='citas.reserva'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicios', to='citas.profesional'),
        ),
        migrations.RunPython(migrar_persona_servicio_a_profesional, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='servicio',
            name='persona_servicio',
        ),
        migrations.AddField(
            model_name='reservahistorialestado',
            name='reserva',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='citas.reserva'),
        ),
        migrations.AddField(
            model_name='reservahistorialestado',
            name='usuario_actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_reserva', to='sesiones.usuario'),
        ),
    ]
