# Generated by Django 6.0.3 on 2026-04-24 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_reserva_profesional'),
    ]

    operations = [
    ]
