# Generated by Django 6.0.3 on 2026-06-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_auto_20260423_1934'),
        ('ventas', '0004_remove_validacionventa_cliente_invitado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cliente_invitado',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='origen_reserva',
            field=models.CharField(choices=[('autenticado', 'Autenticado'), ('admin', 'Administrador')], default='autenticado', max_length=20),
        ),
        migrations.DeleteModel(
            name='ClienteInvitado',
        ),
    ]
