# Generated by Django 6.0.3 on 2026-03-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_devolucioncompra_autorizado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='numero_factura',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='compra',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_factura', ''), _negated=True), fields=('proveedor', 'numero_factura'), name='unique_factura_por_proveedor'),
        ),
    ]
