# Generated by Django 6.0.3 on 2026-03-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_compra_numero_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
