# Generated by Django 6.0.2 on 2026-03-17 22:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-fecha'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='detallecompra',
            options={'verbose_name': 'Detalle de Compra', 'verbose_name_plural': 'Detalles de Compra'},
        ),
        migrations.AlterModelOptions(
            name='devolucioncompra',
            options={'ordering': ['-fecha'], 'verbose_name': 'Devolución de Compra', 'verbose_name_plural': 'Devoluciones de Compra'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de Factura'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='devolucioncompra',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad Devuelta'),
        ),
        migrations.AlterField(
            model_name='devolucioncompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='inventario.compra'),
        ),
        migrations.AlterField(
            model_name='devolucioncompra',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Devolución'),
        ),
        migrations.AlterField(
            model_name='devolucioncompra',
            name='motivo',
            field=models.TextField(blank=True, verbose_name='Motivo de la Devolución'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en Stock'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='NIT/RUC'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre del Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(blank=True, default='Colombia', max_length=100),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='inventario__nombre_2dddb1_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['stock'], name='inventario__stock_0a3383_idx'),
        ),
    ]
