# Generated by Django 6.0.3 on 2026-05-25 17:57

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_lote_especificaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucioncompra',
            options={'ordering': ['-fecha']},
        ),
        migrations.RemoveConstraint(
            model_name='compra',
            name='unique_factura_por_proveedor',
        ),
        migrations.RemoveIndex(
            model_name='inventario',
            name='inv_stock_prod_fecha_idx',
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='inv_prod_act_nom_idx',
        ),
        migrations.AlterField(
            model_name='devolucioncompra',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='devolucioncompra',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='devolucioncompra',
            name='motivo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('DEVOLUCION', 'Devolución')], max_length=15),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
