# Generated by Django 6.0.3 on 2026-03-27 04:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_alter_compra_options_alter_detallecompra_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detallecompra',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='lote',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lote'),
        ),
        migrations.AlterUniqueTogether(
            name='detallecompra',
            unique_together={('compra', 'producto', 'lote')},
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=100, verbose_name='Lote')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock disponible')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de ingreso')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.producto')),
            ],
            options={
                'verbose_name': 'Lote de Inventario',
                'verbose_name_plural': 'Lotes de Inventario',
                'ordering': ['fecha_ingreso', 'id'],
                'unique_together': {('producto', 'lote')},
            },
        ),
    ]
