# Generated by Django 6.0.3 on 2026-03-27 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_detallecompra_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devolucioncompra',
            options={'ordering': ['-fecha'], 'verbose_name': 'Devolucion de Compra', 'verbose_name_plural': 'Devoluciones de Compra'},
        ),
        migrations.RemoveIndex(
            model_name='producto',
            name='inventario__stock_0a3383_idx',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='detallecompra',
            name='forma_pago',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='impuesto',
            field=models.DecimalField(db_column='impuesto', decimal_places=2, default=19, max_digits=5),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='margen_ganancia',
            field=models.DecimalField(db_column='margen_ganancia', decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='margen_ganancia',
            field=models.DecimalField(db_column='margen_ganancia', decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numero de Factura'),
        ),
        migrations.AlterField(
            model_name='devolucioncompra',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Devolucion'),
        ),
        migrations.AlterField(
            model_name='devolucioncompra',
            name='motivo',
            field=models.TextField(blank=True, verbose_name='Motivo de la Devolucion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='iva',
            field=models.DecimalField(db_column='impuesto', decimal_places=2, default=19, max_digits=5, verbose_name='IVA (%)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo Electronico'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creacion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, verbose_name='Razon Social'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
    ]
